services:
  - type: web
    name: campus-nexus-backend
    env: node
    rootDir: project-website
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
